
[[_ratype_ra_interface]]
= Resource Adaptor Interface

The CAP Resource Adaptor SBB Interface provides SBBs with access to the CAP objects required for creating a new, aborting, ending a CAPDialog and sending Request/Response.
It is defined as follows: 

[source,java]
----

package org.restcomm.protocols.ss7.cap.api;

import java.io.Serializable;

import org.restcomm.protocols.ss7.cap.api.errors.CAPErrorMessageFactory;
import org.restcomm.protocols.ss7.cap.api.service.circuitSwitchedCall.CAPServiceCircuitSwitchedCall;
import org.restcomm.protocols.ss7.cap.api.service.gprs.CAPServiceGprs;
import org.restcomm.protocols.ss7.cap.api.service.sms.CAPServiceSms;
import org.restcomm.protocols.ss7.inap.api.INAPParameterFactory;
import org.restcomm.protocols.ss7.isup.ISUPParameterFactory;
import org.restcomm.protocols.ss7.map.api.MAPParameterFactory;

public interface CAPProvider extends Serializable {

	/**
	 * Add CAP Dialog listener to the Stack
	 * 
	 * @param capDialogListener
	 */
	public void addCAPDialogListener(CAPDialogListener capDialogListener);

	/**
	 * Remove CAP DIalog Listener from the stack
	 * 
	 * @param capDialogListener
	 */
	public void removeCAPDialogListener(CAPDialogListener capDialogListener);

	/**
	 * Get the {@link CAPParameterFactory}
	 * 
	 * @return
	 */
	public CAPParameterFactory getCAPParameterFactory();

	/**
	 * Get the {@link MAPParameterFactory}
	 * 
	 * @return
	 */
	public MAPParameterFactory getMAPParameterFactory();

	/**
	 * Get the {@link ISUPParameterFactory}
	 * 
	 * @return
	 */
	public ISUPParameterFactory getISUPParameterFactory();

	/**
	 * Get the {@link INAPParameterFactory}
	 * 
	 * @return
	 */
	public INAPParameterFactory getINAPParameterFactory();

	/**
	 * Get the {@link CAPErrorMessageFactory}
	 * 
	 * @return
	 */
	public CAPErrorMessageFactory getCAPErrorMessageFactory();
	
	/**
	 * Get {@link CAPDialog} corresponding to passed dialogId
	 * 
	 * @param dialogId
	 * @return
	 */
	public CAPDialog getCAPDialog(Long dialogId);

	public CAPServiceCircuitSwitchedCall getCAPServiceCircuitSwitchedCall();
	public CAPServiceGprs getCAPServiceGprs();
	public CAPServiceSms getCAPServiceSms();
		
}
----

public void addCAPDialogListener(CAPDialogListener capDialogListener);::
  this method is not supported.
  Call to it causes NotSupportedException to be thrown.

public void removeCAPDialogListener(CAPDialogListener capDialogListener);::
  this method is not supported.
  Call to it causes NotSupportedException to be thrown.

public CAPParameterFactory getCAPParameterFactory();::
  retrieves factory for generic CAP components

public abstract MAPParameterFactory getMAPParameterFactory();::
  retrieves factory for generic MAP components

public ISUPParameterFactory getISUPParameterFactory();::
  retrieves factory for generic ISUP components

public INAPParameterFactory getINAPParameterFactory();::
  retrieves factory for generic INAP components

public CAPErrorMessageFactory getCAPErrorMessageFactory();::
  retrieves implementation of CAP error message factory.
  Error messages are used to indicate erroneous conditions.

public CAPDialog getCAPDialog(Long dialogId);::
  retrieves active dialog by its `ID`. 

public CAPServiceCircuitSwitchedCall getCAPServiceCircuitSwitchedCall();::
  retrieves CAP Circuit Switch Call service.
  It is used to create circuit switch call related dialogs.

public CAPServiceGprs getCAPServiceGprs();::
  retrieves CAP GPRS Service.
  It is used to create GPPRS handling dialogs.
+
  NOTE: This service is not yet implemented

public CAPServiceSms getCAPServiceSms();::
  retrieves CAP SMS service.
  It is used to create SMS dialogs.
+
  NOTE: This service is not yet implemented

NOTE: As CAP stack is being completed, it will support more services, this list of `getCAPServiceX` will expand to support all implemented services.
