
[[_ratype_ra_interface]]
= Resource Adaptor Interface

The TCAP Resource Adaptor SBB Interface provides SBBs with access to the TCAP objects required for creating a new, aborting, ending a Dialog and sending Request/Response.
It is defined as follows: 

[source,java]
----

package org.restcomm.protocols.ss7.tcap.api;

import java.io.Serializable;

import org.restcomm.protocols.ss7.sccp.parameter.SccpAddress;
import org.restcomm.protocols.ss7.tcap.api.tc.dialog.Dialog;

public interface TCAPProvider extends Serializable {

	/**
	 * Create new structured dialog.
	 * @param localAddress - desired local address
	 * @param remoteAddress - initial remote address, it can change after first TCContinue. 
	 * @return
	 */
	public Dialog getNewDialog(SccpAddress localAddress, SccpAddress remoteAddress) throws TCAPException;
	/**
	 * Create new unstructured dialog.
	 * @param localAddress
	 * @param remoteAddress
	 * @return
	 * @throws TCAPException
	 */
	public Dialog getNewUnstructuredDialog(SccpAddress localAddress, SccpAddress remoteAddress) throws TCAPException;

	///////////////
	// Factories //
	///////////////
	
	public DialogPrimitiveFactory getDialogPrimitiveFactory();
	public ComponentPrimitiveFactory getComponentPrimitiveFactory();
	
	///////////////
	// Listeners //
	///////////////	
	
	public void addTCListener(TCListener lst);

	public void removeTCListener(TCListener lst);

	public boolean getPreviewMode();
}
----

public void addTCListener(TCListener lst);::
  this method is not supported.
  Call to it causes NotSupportedException to be thrown.

public void removeTCListener(TCListener lst);::
  this method is not supported.
  Call to it causes NotSupportedException to be thrown.

public DialogPrimitiveFactory getDialogPrimitiveFactory();::
  retrieves factory for creating Dialog primitives

public ComponentPrimitiveFactory getComponentPrimitiveFactory();::
  retrieves factory for creating components

public Dialog getNewDialog(SccpAddress localAddress, SccpAddress remoteAddress) throws TCAPException;::
  Creates new structured Dialog

public Dialog getNewUnstructuredDialog(SccpAddress localAddress, SccpAddress remoteAddress) throws TCAPException;::
  Creates new unstructured dialog

public boolean getPreviewMode();::
  Returns true if this TCAP stack is configured as preview